# Generated by Django 4.0.1 on 2022-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='snap_chat',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/user/authors'),
        ),
    ]
