# Generated by Django 4.0.1 on 2022-03-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_github_remove_profile_snap_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='short_intro',
        ),
    ]
