# Generated by Django 4.0.1 on 2022-03-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_name_profile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
