# Generated by Django 4.0.4 on 2022-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_github_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blogging/authors'),
        ),
    ]
