# Generated by Django 4.0.4 on 2022-05-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_email_alter_profile_auth_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Email',
            new_name='gmail',
        ),
    ]
