# Generated by Django 4.0.4 on 2022-05-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_email_profile_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gmail',
        ),
    ]
