# Generated by Django 4.0.4 on 2022-05-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_profile_gmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='mail',
        ),
    ]
