# Generated by Django 4.0.4 on 2022-05-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_email_profile_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail',
            new_name='gmail',
        ),
    ]
