# Generated by Django 4.0.4 on 2022-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_profile_user_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_image',
            field=models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to='static/blogging/authors'),
        ),
    ]
