# Generated by Django 4.0.6 on 2022-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_rename_full_name_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Ids',
            field=models.SlugField(default=100),
            preserve_default=False,
        ),
    ]
