# Generated by Django 4.0.6 on 2022-07-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_profile_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Ids',
        ),
    ]
