# Generated by Django 4.0.1 on 2022-03-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_user'),
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
