# Generated by Django 4.0.1 on 2022-03-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blogging/images'),
        ),
    ]
