# Generated by Django 4.0.4 on 2022-05-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_name_profile_username'),
        ('blogging', '0006_rename_tag_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
