# Generated by Django 4.0.4 on 2022-05-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='linkedin',
        ),
    ]
