# Generated by Django 4.0.6 on 2022-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0012_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to='static/blogging/'),
        ),
    ]
