# Generated by Django 3.2.12 on 2023-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0015_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to=''),
        ),
    ]
