# Generated by Django 3.2.12 on 2023-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0016_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.DateField(auto_now_add=True),
        ),
    ]
