# Generated by Django 3.2.12 on 2023-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0017_alter_blog_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
